language: node_js
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g yarn --cache-min "999999999"
node_js: '7'
install: yarn
before_deploy:
- yarn run build-storybook
deploy:
  provider: npm
  email: jacklam718@gmail.com
  api_key:
    secure: Fney0SBXsPAVZG/q1PmWfwy5cFs3SNIYI6K/OjTnoELg1AqXdsrDe9FsOOteFHlXO4Qvnxw+4D8uP7PQKP8EbhnP9n5UqM/qzEozQYDGsWYSonPjE4CQs2glTMvISBhbKekay1BUJ+djcS1cuO4QEQOMFTZHD2ajfRrOjbItHowCvt+1KoxS+SVa9Ybu7q0FzVbJkLZInSQQnRzykyIl+D6PVn6uPwed+XoW0CsH1k07wFwObp9KHBZeE9Zdsl8OG0VJQK7GhGX3ZubyRoQs7aiBlqlWs72rGOF+KDX/+vbJDr1jJ1S+cIU/XgHqslaq+Wtxf5A8ThMmDNwIauMqf2nU7F5hdlvYBQDatLmZGqJ/S1a5ayYzcwF0YlPU3w3aO+0ATh13g7CrUsGov4Zlp88TLpkiBsIBXj4N9tdxmkwKljosUAV/hV9knFHXnKrIaioxaL4s+yX6TefQtnRRYhQ7aZjw8ToHhwPzVw3BoDWfSptDQNhOlTxL0IpzILz/t7C0LLSoVTLXQ29h/lvGIwo6hKiLD1p6fGujWwFFQEF56LEAyzVo7rKyUWgOI8YpxDIf0+pHgyowvuAp1qRfOnsRiMn3gJBSr/OkVV6l7uKq9oYs1c1UIHR0nOVhJutaFUvZrzf2AZqkqE50fAqpENV9WPBEP7Mc4ecW8GOBN9o=
  on:
    tags: true
    repo: jacklam718/react-svg-iconx
