language: node_js
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g yarn --cache-min "999999999"
node_js: '7'
install: yarn
before_deploy:
  - yarn run build-storybook
deploy:
  provider: npm
  email: jacklam718@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: jacklam718/react-svg-iconx
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: $GITHUB_TOKEN
  on:
    branch: master
