language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - storybook-static
before_install:
  - npm install -g yarn --cache-min "999999999"
node_js: '7'
install: yarn
after_success:
  - rm -rf build &&
    cp -r dist build &&
    cp LICENSE README.md package.json build
before_deploy:
  - yarn run build-storybook &&
    cd build
deploy:
  - provider: npm
    skip_cleanup: true
    email: jacklam718@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: jacklam718/react-svg-iconx
      all_branches: true
  - provider: pages
    skip_cleanup: true
    local_dir: ../storybook-static
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      repo: jacklam718/react-svg-iconx
